// src/app/layout.tsx
import Navbar from "../components/Navbar"; // Import the Navbar component
import { Geist, Geist_Mono } from "next/font/google"; // Your font imports

// Font configuration
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout with Navbar
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar /> {/* Add the Navbar at the top */}
        <main>{children}</main> {/* The rest of the page content */}
      </body>
    </html>
  );
}
